version: "3.7"

services:

  db:
    image: mariadb:latest
    restart: on-failure
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=planeinvoice
      - MYSQL_DATABASE=invoiceplane
    volumes:
      - db:/var/lib/mysql

  invoiceplane:
    build: .
    image: invoiceplane
    entrypoint: ["./wait-for", "db:3306", "--", "lighttpd"]
    command: ["-D", "-f", "/etc/lighttpd/lighttpd.conf"]
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /data/InvoicePlane/db
      o: bind
